
import { AppSettings, User, TranslationKey } from './types';

export const DEFAULT_USERS: User[] = [
  { id: 1, name: 'Admin', email: 'admin@ysn.com', role: 'admin', active: true },
  { id: 2, name: 'John Editor', email: 'john@ysn.com', role: 'editor', active: true },
  { id: 3, name: 'Jane Viewer', email: 'jane@ysn.com', role: 'viewer', active: false }
];

export const DEFAULT_SETTINGS: AppSettings = {
  categories: ['Manager', 'Employé', 'Stagiaire', 'Contractuel'],
  shifts: [
    { name: 'Matin', start: '06:00', end: '14:00', color: '#3b82f6' }, // Blue
    { name: 'Après-midi', start: '14:00', end: '22:00', color: '#f59e0b' }, // Amber
    { name: 'Nuit', start: '22:00', end: '06:00', color: '#8b5cf6' } // Purple
  ],
  assignments: ['Ressources Humaines', 'Informatique', 'Ventes', 'Marketing', 'Finance'],
  absenceTypes: [
    { name: 'Repos', color: '#9ca3af' }, // Gray
    { name: 'Récupération', color: '#6366f1' }, // Indigo
    { name: 'Maladie', color: '#ef4444' }, // Red
    { name: 'Absence', color: '#b91c1c' }, // Dark Red
    { name: 'Formation', color: '#10b981' }, // Emerald
    { name: 'Congé', color: '#14b8a6' } // Teal
  ],
  holidays: [],
  dateFormat: 'DD/MM/YYYY',
  language: 'en' // Default to English
};

export const formatDisplayDate = (dateStr: string | undefined | null, format: string) => {
  if (!dateStr) return '-';
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) return dateStr;

  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();

  if (format === 'MM/DD/YYYY') return `${month}/${day}/${year}`;
  if (format === 'DD/MM/YYYY') return `${day}/${month}/${year}`;
  // Default YYYY-MM-DD
  return `${year}-${month}-${day}`;
};

export const TRANSLATIONS: Record<'fr' | 'en', Record<TranslationKey, string>> = {
  fr: {
    home: 'Accueil',
    dashboard: 'Tableau de bord',
    employees: 'Collaborateurs',
    planning: 'Planning',
    settings: 'Paramètres',
    users: 'Utilisateurs',
    bonus: 'Primes',
    audit: 'Traçabilité',
    training: 'Formations',
    logout: 'Déconnexion',
    search: 'Rechercher...',
    new_employee: 'Nouveau collaborateur',
    filter_category: 'Toutes les catégories',
    filter_employee: 'Rechercher un employé...',
    filter_team: 'Toutes les équipes',
    stats_total: 'Total Collaborateurs',
    stats_present: 'Présents Aujourd\'hui',
    stats_absent: 'Absents / Repos',
    welcome_title: 'Bienvenue sur Team LP',
    welcome_subtitle: 'Gérez votre personnel simplement',
    quick_access: 'Accès Rapide',
    recent_activity: 'Activité Récente',
    general_settings: 'Préférences Générales',
    app_data: 'Données de l\'application',
    teams: 'Gestion des Équipes',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    create: 'Créer',
    update: 'Mettre à jour',
    reset: 'Réinitialiser',
    bonus_management: 'Suivi des Primes',
    bonus_eligible: 'Éligible à la prime',
    score: 'Note / Prime',
    select_team: 'Sélectionner une équipe',
    audit_title: 'Journal d\'audit',
    audit_subtitle: 'Historique des modifications du système',
    action: 'Action',
    date: 'Date',
    details: 'Détails',
    user: 'Utilisateur',
    edit_team: 'Modifier l\'équipe',
    create_team: 'Créer une équipe',
    team_name: 'Nom de l\'équipe',
    team_leader: 'Responsable',
    team_members: 'Membres',
    exit_date: 'Date de sortie',
    entry_date: 'Date d\'entrée',
    exit_management: 'Gestion de sortie',
    set_exit_date: 'Définir date de sortie',
    active_status: 'Statut',
    holidays: 'Jours Fériés',
    absence_types: 'Motifs d\'absence',
    history: 'Historique',
    filter_name_code: 'Nom ou Matricule...',
    rows_per_page: 'Lignes par page',
    all: 'Tout',
    showing_range: 'Affichage de {start} à {end} sur {total}',
    filter_action: 'Type d\'action',
    filter_user: 'Utilisateur',
    filter_date: 'Date',
    start_date: 'Du',
    end_date: 'Au',
    view_calendar: 'Vue Calendrier',
    view_grid: 'Vue Grille',
    export_pdf: 'PDF',
    export_image: 'Image',
    color: 'Couleur',
    error_entry_before_birth: 'La date d\'entrée doit être postérieure à la date de naissance.',
    error_exit_before_birth: 'La date de sortie doit être postérieure à la date de naissance.',
    error_exit_before_entry: 'La date de sortie doit être postérieure à la date d\'entrée.',
    export: 'Exporter',
    assign_to: 'Assigner à',
    status_planned: 'Planifiée',
    status_in_progress: 'En cours',
    status_validated: 'Validée',
    status_archived: 'Archivée',
    training_title: 'Titre',
    training_sessions: 'Séances',
    training_target: 'Cible',
    training_participants: 'Participants',
    training_attendance: 'Présence',
    manage_participants: 'Gérer les participants',
    mark_attendance: 'Noter la présence',
    validate_step: 'Valider l\'étape',
    archive: 'Archiver',
    back_step: 'Retour étape préc.',
    training_dashboard: 'Tableau de Bord des Formations',
    beneficiaries: 'Bénéficiaires',
    training_history: 'Historique des Formations',
    attendees: 'Présents'
  },
  en: {
    home: 'Home',
    dashboard: 'Dashboard',
    employees: 'Employees',
    planning: 'Schedule',
    settings: 'Settings',
    users: 'Users',
    bonus: 'Bonuses',
    audit: 'Audit Log',
    training: 'Training',
    logout: 'Logout',
    search: 'Search...',
    new_employee: 'New Employee',
    filter_category: 'All Categories',
    filter_employee: 'Search employee...',
    filter_team: 'All Teams',
    stats_total: 'Total Employees',
    stats_present: 'Present Today',
    stats_absent: 'Absent / Off',
    welcome_title: 'Welcome to Team LP',
    welcome_subtitle: 'Manage your staff simply',
    quick_access: 'Quick Access',
    recent_activity: 'Recent Activity',
    general_settings: 'General Preferences',
    app_data: 'Application Data',
    teams: 'Team Management',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    create: 'Create',
    update: 'Update',
    reset: 'Reset',
    bonus_management: 'Bonus Tracking',
    bonus_eligible: 'Eligible for bonus',
    score: 'Score / Bonus',
    select_team: 'Select a team',
    audit_title: 'Audit Log',
    audit_subtitle: 'System modification history',
    action: 'Action',
    date: 'Date',
    details: 'Details',
    user: 'User',
    edit_team: 'Edit Team',
    create_team: 'Create Team',
    team_name: 'Team Name',
    team_leader: 'Team Leader',
    team_members: 'Members',
    exit_date: 'Exit Date',
    entry_date: 'Entry Date',
    exit_management: 'Exit Management',
    set_exit_date: 'Set Exit Date',
    active_status: 'Status',
    holidays: 'Public Holidays',
    absence_types: 'Absence Types',
    history: 'History',
    filter_name_code: 'Name or ID...',
    rows_per_page: 'Rows per page',
    all: 'All',
    showing_range: 'Showing {start} to {end} of {total}',
    filter_action: 'Action Type',
    filter_user: 'User',
    filter_date: 'Date',
    start_date: 'From',
    end_date: 'To',
    view_calendar: 'Calendar View',
    view_grid: 'Grid View',
    export_pdf: 'PDF',
    export_image: 'Image',
    color: 'Color',
    error_entry_before_birth: 'Entry date must be after birth date.',
    error_exit_before_birth: 'Exit date must be after birth date.',
    error_exit_before_entry: 'Exit date must be after entry date.',
    export: 'Export',
    assign_to: 'Assign to',
    status_planned: 'Planned',
    status_in_progress: 'In Progress',
    status_validated: 'Validated',
    status_archived: 'Archived',
    training_title: 'Title',
    training_sessions: 'Sessions',
    training_target: 'Target',
    training_participants: 'Participants',
    training_attendance: 'Attendance',
    manage_participants: 'Manage Participants',
    mark_attendance: 'Mark Attendance',
    validate_step: 'Validate Step',
    archive: 'Archive',
    back_step: 'Step Back',
    training_dashboard: 'Training Dashboard',
    beneficiaries: 'Beneficiaries',
    training_history: 'Training History',
    attendees: 'Present'
  }
};
